import type { Metadata } from "next";
import { Roboto_Flex } from 'next/font/google'
import "./globals.css";

const roboto = Roboto_Flex({
  subsets: ["latin", "cyrillic"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Vegas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="md:bg-foreground scroll-smooth">
      <body className={`antialiased ${roboto.className}`}>
        {children}
      </body>
    </html>
  );
}
