import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "./globals.css";
import Footer from "./components/footer";

const roboto = Roboto({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Vegas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="md:bg-foreground scroll-smooth">
      <body className={`flex flex-col min-h-svh antialiased ${roboto.className}`}>
        <div className={'flex-grow'}>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
